Pour etre au plus proche du KNX, le plugin peut ce comporter comme un participant.
On peut donc configurer le plugin pour qui realise de action automatiquement

=== Envoyer sur le bus une valeur
Vous avez sur votre jeedom un capteur qui n'est pas KNX, mais vous souhaité le liée directement a votre réseau.
Vous pouvez le faire directement depuis le plugin en configurant ainsi votre commande

* Cree une commande de type "action"
* Saisir le GAD qui correspond a l'objet KNX que vous voulez mettre a jours
* Activer le Flag "Transmettre"
* En retour d'etat allez chercher la commande de votre capteur

=== Executer des actions a la mise a jours

Vous avez un interrupteur KNX et vous voulez declanché un scénrio ou un commande jeedom
Vous pouvez le faire directement depuis le plugin en configurant ainsi votre commande

* Cree une commande de type "info"
* Saisir le GAD qui correspond a l'objet KNX que vous voulez surveiller
* Activer le flag "Ecriture"
* Saisir la liste des actions a mener

=== Reponse a une commande Read du bus

Le plugin est capable de repondre a un interrogation du bus
Vous pouvez le faire directement depuis le plugin en configurant ainsi votre commande
* Cree une commande de type "info"
* Saisir le GAD qui correspond a l'objet KNX que vous voulez surveiller
* Activer le flag "Lecture"
